name = "ada_snake"
description = "Test of ncurses"
version = "0.1.0-dev"

authors = ["Jay Nabonne"]
maintainers = ["Jay Nabonne <jaynabonne@gmail.com>"]
maintainers-logins = ["jaynabonne"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["ada_snake"]

[[depends-on]]
ncursesada = "^6.5.0"
